Agency/Agency/Controllers/AddAdController.cs
using Agency.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace Agency.Controllers
{
    public class AddAdController : Controller
    {
        private agencyEntities db = new agencyEntities();
        // GET: AddAd
        public ActionResult Index()
        {           
            List<Ad> ad = db.Ads.Where(c => c.PUBLISHED == true).ToList();                               
            return View(ad);
        }

        // GET: AddAd/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AddAd/Create
        public ActionResult Create()
        {
            ViewBag.DISCOUNT = new SelectList(db.DISCOUNTs, "Id", "Value");
            ViewBag.OBJECT_KIND = new SelectList(db.OBJECT_KIND, "Id", "NAME");
            ViewBag.OBJECT_TYPE = new SelectList(db.OBJECT_TYPE, "Id", "NAME");
            ViewBag.AD_TYPE = new SelectList(db.AD_TYPE, "Id", "NAME");
            return View();
        }

        // POST: AddAd/Create
        [HttpPost]
        public ActionResult Create(AddAdModel model)
        {
            try
            {           
                foreach (var i in model.Files)
                {
                    if (i.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(i.FileName);
                        var fileNameWithPath = Path.Combine(Server.MapPath("~/Files"), fileName);
                        i.SaveAs(fileNameWithPath);
                        //Make filepath relative
                        Uri fromPath = new Uri(fileNameWithPath);
                        Uri toPath = new Uri(Server.MapPath("./Files"));
                        Uri path = toPath.MakeRelativeUri(fromPath);
                        model.obj.IMAGE += path + ";";
                        //String path = UploadImage(i);
                    }
                }
                model.advert.ADDITION_DATE = DateTime.Today;
                db.OBJs.Add(model.obj);
                db.SaveChanges();             
                model.advert.OBJECT_ID = model.obj.Id;
                db.Ads.Add(model.advert);
                db.SaveChanges();
                return RedirectToAction("Index", "Ads");
            }
            catch (Exception exc)
            {
                Console.WriteLine(exc.ToString());
                ViewBag.DISCOUNT = new SelectList(db.DISCOUNTs, "Id", "Value");
                ViewBag.OBJECT_KIND = new SelectList(db.OBJECT_KIND, "Id", "NAME");
                ViewBag.OBJECT_TYPE = new SelectList(db.OBJECT_TYPE, "Id", "NAME");
                ViewBag.AD_TYPE = new SelectList(db.AD_TYPE, "Id", "NAME");
                return View();
            }
        }


        public string UploadImage(HttpPostedFileBase image)
        {
            var httpWReq =
                (HttpWebRequest)WebRequest.Create("http://www.imageshack.us/upload_api.php");

            httpWReq.Method = "POST";
            httpWReq.ContentType = "multipart/form-data";
            httpWReq.KeepAlive = true;

            var stream = httpWReq.GetRequestStream();
            var encoding = new UTF8Encoding();
            var postData = "key=GZC2V0FT62e1caa7d54d699a56959989f31a5af2";
            postData += "&fileupload=";
            byte[] data = encoding.GetBytes(postData);
            stream.Write(data, 0, data.Length);
            var buffer = new byte[4096];
            int bytesread;
            while ((bytesread = image.InputStream.Read(buffer, 0, buffer.Length)) != 0)
            {
                stream.Write(buffer, 0, bytesread);
            }
            stream.Close();


            var response = (HttpWebResponse)httpWReq.GetResponse();

            string responseString = new StreamReader(response.GetResponseStream()).ReadToEnd();
            return responseString;
        }

        // GET: AddAd/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AddAd/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: AddAd/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AddAd/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Agency/Agency/Views/AddAd/Create.cshtml
@model Agency.Models.AddAdModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/File")
    <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
   
}


<style>
    .stationInfo {
        height: 150px;
        width: 250px;
    }
</style>

<h2>Create</h2>

@using (Html.BeginForm("Create", "AddAd", FormMethod.Post, new { encType = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ad</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<input type="file" name="files" id="files" multiple />*@

       @Html.TextBoxFor(m => m.Files, new {id="files", type = "file", name = "Files", multiple = "" })

        <div id="filePreview"></div>

        <div class="form-group">
            @Html.LabelFor(model => model.advert.AD_TYPE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.advert.AD_TYPE_ID, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.advert.AD_TYPE_ID, (SelectList)ViewBag.AD_TYPE)
                @Html.ValidationMessageFor(model => model.advert.AD_TYPE_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.advert.TITLE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.advert.TITLE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.advert.TITLE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.advert.DESCRIPTION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.advert.DESCRIPTION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.advert.DESCRIPTION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.advert.PRICE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.advert.PRICE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.advert.PRICE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.advert.PUBLISHED, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.advert.PUBLISHED)
                    @Html.ValidationMessageFor(model => model.advert.PUBLISHED, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.obj.OBJECT_KIND, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.advert.AD_TYPE_ID, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.obj.KIND_ID, (SelectList)ViewBag.OBJECT_KIND)
                @Html.ValidationMessageFor(model => model.obj.TYPE_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.obj.OBJECT_TYPE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.advert.AD_TYPE_ID, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.obj.TYPE_ID, (SelectList)ViewBag.OBJECT_TYPE)
                @Html.ValidationMessageFor(model => model.obj.TYPE_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.advert.DISCOUNT1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.advert.AD_TYPE_ID, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.advert.DISCOUNT_ID, (SelectList)ViewBag.DISCOUNT)
                @Html.ValidationMessageFor(model => model.advert.DISCOUNT_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">          
            <div class="col-md-10">
                @Html.HiddenFor(model => model.obj.GeoLat, new { id = "hiddenGeoLat" })
                @Html.HiddenFor(model => model.obj.GeoLong, new { id = "hiddenGeoLong" })
                @Html.HiddenFor(model => model.obj.ADDRESS, new { id = "hiddenAddress" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.obj.FLOOR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.obj.FLOOR, new SelectList(new List<SelectListItem>
           {
               new SelectListItem {Text = "1", Value = "1"},
               new SelectListItem {Text = "2",  Value = "2" },
               new SelectListItem {Text = "3",  Value = "3" },
               new SelectListItem {Text = "4",  Value = "4" },
               new SelectListItem {Text = "5",  Value = "5" },
               new SelectListItem {Text = "6",  Value = "6" },
               new SelectListItem {Text = "7",  Value = "7" },
               new SelectListItem {Text = "8",  Value = "8" },
               new SelectListItem {Text = "9",  Value = "9" },
               new SelectListItem {Text = "10",  Value = "10" },
               new SelectListItem {Text = "11",  Value = "11" },
               new SelectListItem {Text = "12",  Value = "12" }
           }, "Value", "Text", 1), String.Empty, new { id = "textddl", @class = "col-xs-12" })
                @Html.ValidationMessageFor(model => model.obj.FLOOR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.obj.ROOMS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.obj.ROOMS, new SelectList(new List<SelectListItem>
           {
               new SelectListItem {Text = "1", Value = "1"},
               new SelectListItem {Text = "2",  Value = "2" },
               new SelectListItem {Text = "3",  Value = "3" },
               new SelectListItem {Text = "4",  Value = "4" },
               new SelectListItem {Text = "5",  Value = "5" },
               new SelectListItem {Text = "6",  Value = "6" },
               new SelectListItem {Text = "7",  Value = "7" },
               new SelectListItem {Text = "8",  Value = "8" },
               new SelectListItem {Text = "9",  Value = "9" },
               new SelectListItem {Text = "10",  Value = "10" }       
           }, "Value", "Text", 1), String.Empty, new { id = "textddl", @class = "col-xs-12" })
                @Html.ValidationMessageFor(model => model.obj.ROOMS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.advert.ADDITION_DATE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.advert.AD_TYPE_ID, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.EditorFor(model => model.advert.ADDITION_DATE)
                @Html.ValidationMessageFor(model => model.advert.ADDITION_DATE, "", new { type="date" })
            </div>
            @Html.Label("Дата начала публикации объявления")
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.advert.EXPIRED_DATE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.advert.AD_TYPE_ID, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.EditorFor(model => model.advert.EXPIRED_DATE)
                @Html.ValidationMessageFor(model => model.advert.EXPIRED_DATE, "", new { type="date" })
            </div>
            @Html.Label("Дата снятия объявления с публикации")
        </div>

        <div id="map" style="width:600px; height:500px"></div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" id="subm" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Agency/Agency/Views/AddAd/Index.cshtml
@model IEnumerable<Agency.Models.Ad>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.advert.AD_TYPE_ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.advert.TITLE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.advert.DESCRIPTION)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.advert.PRICE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.obj.FLOOR)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.obj.ADDRESS)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.obj.ROOMS)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.obj.OBJECT_KIND.NAME)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.obj.OBJECT_TYPE.NAME)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.obj.IMAGE)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.advert.AD_TYPE_ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.advert.TITLE)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.advert.DESCRIPTION)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.advert.PRICE)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.advert.PUBLISHED)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.advert.OBJECT_ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.obj.FLOOR)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.obj.ADDRESS)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.obj.ROOMS)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.obj.OBJECT_KIND.NAME)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.obj.OBJECT_TYPE.NAME)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.obj.IMAGE)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.advert.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.advert.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.advert.Id })
            </td>
        </tr>
    }

</table>